/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myfiles.BR;

/**
 *
 * @author CL3-PC16
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(453, 715));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 140));

        jButton1.setText("CE");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, 40));

        jButton3.setText("⌫");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, 40));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("%");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 40));

        jButton6.setText("C");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 90, 40));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText(" x²");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 90, 40));

        jButton8.setText("²⟌x");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 90, 40));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton9.setText("÷");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 40));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setText("¹⁄x");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 40));

        jButton11.setText("SAVE");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 40));

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton13.setText("8");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, 40));

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton15.setText("×");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 90, 40));

        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton17.setText("7");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 40));

        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton18.setText("9");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 90, 40));

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton19.setText("5");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 90, 40));

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton20.setText("6");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 90, 40));

        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton21.setText("-");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, 40));

        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton23.setText("4");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 40));

        jButton25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton25.setText("2");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 90, 40));

        jButton26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton26.setText("3");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 90, 40));

        jButton27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton27.setText("+");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, 40));

        jButton28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton28.setText("1");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, 40));

        jButton29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton29.setText("0");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 90, 40));

        jButton30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton30.setText(".");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 90, 40));

        jButton31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton31.setText("=");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 40));

        jButton32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton32.setText("⁺/₋");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 40));

        jButton2.setText("MC");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 30));

        jButton4.setText("MR");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, 30));

        jButton14.setText("M+");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 60, 30));

        jButton16.setText("M-");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 60, 30));

        jButton22.setText("MS");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 60, 30));

        jButton24.setText("M˅ ");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 60, 30));

        setSize(new java.awt.Dimension(398, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
